# 重载配置文件
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Tmux config reloaded"

# 分割窗口
unbind v
unbind h
unbind % # 纵向分割
unbind '"' # 横向分割
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# 窗口导航
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# 历史
set -g history-limit 100000

# 窗口
unbind n
unbind w
bind n command-prompt "rename-window '%%'"
bind w new-window -c "#{pane_current_path}"

# 标签
set -g base-index 1
set-window-option -g pane-base-index 1

# 窗口移动
bind -n M-j previous-window
bind -n M-k next-window

# 复制粘贴
set-window-option -g mode-keys vi
unbind -T copy-mode-vi Space
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

# 终端模拟修复
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Vim集成
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

# 终端颜色
set -g default-terminal "screen-256color"

# 插件
# 如果未安装插件管理器则自动安装插件管理器并安装插件
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"
# 设置插件安装位置
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
# 前缀键提示
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
# 会话保存
set -g @plugin 'tmux-plugins/tmux-resurrect'
# 自动保存会话
set -g @plugin 'tmux-plugins/tmux-continuum'
# 复制粘贴增强
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
# 侧边栏
set -g @plugin 'tmux-plugins/tmux-sidebar'
# CPU/GPU信息
set -g @plugin 'tmux-plugins/tmux-cpu'
# 电池信息
set -g @plugin 'tmux-plugins/tmux-battery'
# 类Vimium复制粘贴提示
set -g @plugin 'Morantron/tmux-fingers'
# 运行插件管理器
run '~/.local/share/tmux/plugins/tpm/tpm'

# 自动保存设置
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @continuum-save-uptime 'on'
