(require 'vertico)
(define-key vertico-map "C-j" 'vertico-next)
(define-key vertico-map "C-k" 'vertico-previous)
(define-key vertico-map "C-f" 'vertico-exit-input)
(define-key minibuffer-local-map "M-h" 'vertico-directory-up)
(setq vertico-cycle t)
(vertico-mode)

(require 'corfu)
(define-key corfu-map "C-j" 'corfu-next)
(define-key corfu-map "C-k" 'corfu-previous)
(define-key corfu-map "TAB" 'corfu-insert)
(define-key corfu-map "C-f" 'corfu-insert)
(setq corfu-cycle t)
(setq corfu-auto t)
(setq corfu-preview-current nil)
(setq corfu-quit-at-bounary t)
(setq corfu-quit-no-match t)
(global-corfu-mode)
(defun corfu-enable-in-minibuffer ()
  (when (where-is-internal #'completion-at-point (list (current-local-map)))
    (setq-local corfu-echo-delay nil)
    (setq-local corfu-popupinfo-delay nil)
    (corfu-mode)))
(add-hook 'minibuffer-setup-hook #'corfu-enable-in-minibuffer)

(require 'orderless)
(setq completion-styles '(orderless))
(setq completion-category-defaults nil)
(setq orderless-matching-styles '(orderless-literal orderless-regexp))
(setq completion-category-overrides '((file (styles partial-completion))))

(require 'consult)
(require 'consult-dir)
(global-set-key (kbd "C-s") 'consult-line)
(global-set-key (kbd "C-M-l") 'consult-imenu)
(global-set-key (kbd "C-x C-b") 'consult-buffer)
(define-key minibuffer-local-map "C-r" 'consult-history)
(setq completion-in-region-function #'consult-completion-in-region)
(global-set-key (kbd "C-x C-d") 'consult-dir)
(define-key vertico-map (kbd "C-x C-d") 'consult-dir)
(define-key vertico-map (kbd "C-x C-j") 'consult-dir-jump-file)
(setq consult-dir-project-list-function nil)

(require 'marginalia)
(setq marginalia-annotators '(marginalia-annotators-heavy
			      marginalia-annotators-light
			      nil))
(marginalia-mode)

(require 'embark)
(global-set-key (kbd "C-M-.") 'embark-act)
(define-key minibuffer-local-map "C-d" 'embark-act)
(setq prefix-help-command #'embark-prefix-help-command)
(provide 'init-completion)
